import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDown, ArrowRight, ArrowUpRight, Menu, X, Scale, ShieldCheck, FileText, Landmark, Building2, HeartHandshake, ChevronDown, Phone, Mail, MapPin, Clock, Instagram, Linkedin } from 'lucide-react';
import './styles.css';
import Admin from './Admin';
import {loadContent, loadRequests} from './content';

const services = [
  {icon: Landmark, n:'01', title:'Droit des affaires', text:'Sécuriser vos décisions, structurer vos projets et accompagner la vie de votre entreprise.'},
  {icon: FileText, n:'02', title:'Droit immobilier', text:'Acquisition, vente, baux et opérations immobilières suivis avec méthode et précision.'},
  {icon: HeartHandshake, n:'03', title:'Droit de la famille', text:'Vous conseiller dans les moments importants et protéger durablement vos intérêts.'},
  {icon: ShieldCheck, n:'04', title:'Conseil & contentieux', text:'Une stratégie claire, une défense engagée et un accompagnement à chaque étape.'}
];

function Intro({onDone}) {
  useEffect(() => { const t=setTimeout(onDone, 3100); return ()=>clearTimeout(t); }, [onDone]);
  return <div className="intro" aria-label="Ouverture du cabinet">
    <div className="intro-mark"><div className="seal"><Scale size={46} strokeWidth={1.1}/></div><div className="intro-line"/></div>
    <p className="eyebrow intro-eyebrow">ÉTUDE & CONSEIL</p>
    <p className="intro-caption">LA JUSTESSE DU DROIT. LA FORCE DU CONSEIL.</p>
    <div className="intro-progress"><i/></div>
  </div>;
}
function Header({openBooking, identity}) {
  const [open,setOpen]=useState(false);
  const close=()=>setOpen(false);
  return <header className="header"><a href="#accueil" className="brand" onClick={close}><span className="brand-icon"><Scale size={24}/></span><span><b>{identity.name}</b><small>{identity.type}</small></span></a>
    <button className="menu-toggle" onClick={()=>setOpen(!open)} aria-label="Ouvrir le menu">{open?<X/>:<Menu/>}</button>
    <nav className={open?'nav open':'nav'}><a href="#cabinet" onClick={close}>Le cabinet</a><a href="#expertises" onClick={close}>Nos expertises</a><a href="#equipe" onClick={close}>L’équipe</a><a href="#actualites" onClick={close}>Conseils</a><button className="nav-cta" onClick={()=>{close();openBooking()}}>Prendre rendez-vous <ArrowUpRight size={15}/></button></nav>
  </header>;
}
function BookingModal({onClose, services, onSubmit, availability}) {
  const [sent,setSent]=useState(false);
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="booking-modal"><button className="modal-close" onClick={onClose}><X/></button>{sent?<div className="success"><div className="success-icon"><ShieldCheck/></div><p className="eyebrow">DEMANDE ENREGISTRÉE</p><h2>Merci pour votre confiance.</h2><p>Notre équipe vous recontactera dans les meilleurs délais pour confirmer votre rendez-vous.</p><button className="button dark" onClick={onClose}>Fermer <ArrowRight size={16}/></button></div>:<><p className="eyebrow">PARLONS DE VOTRE SITUATION</p><h2>Demander un rendez-vous</h2><p className="modal-sub">Décrivez brièvement votre besoin. Le cabinet vous recontactera pour convenir d’un créneau.</p><form onSubmit={e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));onSubmit(data);setSent(true)}}><div className="form-row"><label>Nom complet<input name="name" required placeholder="Votre nom"/></label><label>Téléphone<input name="phone" required type="tel" placeholder="+225 07 00 00 00 00"/></label></div><label>Adresse e-mail<input name="email" type="email" required placeholder="vous@exemple.com"/></label><label>Objet de la demande<select name="subject" required defaultValue=""><option value="" disabled>Choisissez un domaine</option>{services.map(item=><option key={item.title}>{item.title}</option>)}<option>Autre demande</option></select></label><label>Mode de consultation<select name="mode"><option>Au cabinet</option><option>Par téléphone</option><option>Visioconférence</option></select></label><p className="form-note">{availability.days} · {availability.note}</p><label>Quelques mots sur votre demande<textarea name="message" rows="3" placeholder="Votre message (sans informations confidentielles)…"/></label><button className="button dark full" type="submit">Envoyer ma demande <ArrowRight size={16}/></button><small className="form-note">Ce formulaire ne constitue pas une consultation juridique et ne crée pas de relation avocat-client.</small></form></>}</section></div>;
}
function App(){
  const [intro,setIntro]=useState(!window.matchMedia('(prefers-reduced-motion: reduce)').matches);const [booking,setBooking]=useState(false);const [admin,setAdmin]=useState(location.hash==='#admin');const [content,setContent]=useState(loadContent);const [requests,setRequests]=useState(loadRequests);const {identity,services:editableServices,team,articles,faq,availability}=content;const submitRequest=data=>{const next=[{...data,id:crypto.randomUUID(),createdAt:new Date().toISOString(),status:'Nouveau'},...requests];setRequests(next);localStorage.setItem('legal-requests',JSON.stringify(next))};
  useEffect(()=>{document.body.style.overflow=!admin&&(booking||intro)?'hidden':'';return()=>document.body.style.overflow='';},[booking,intro,admin]);
  useEffect(()=>{const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>obs.observe(el));return()=>obs.disconnect()},[intro,admin]);
  useEffect(()=>{const onHash=()=>setAdmin(location.hash==='#admin');window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash)},[]);
  if(admin)return <Admin content={content} setContent={setContent} requests={requests} setRequests={setRequests} onBack={()=>{location.hash='#accueil';setAdmin(false);setIntro(false)}}/>;
  return <>
    {intro&&<Intro onDone={()=>setIntro(false)}/>}
    <Header identity={identity} openBooking={()=>setBooking(true)}/>
    <main>
      <section className="hero" id="accueil"><div className="hero-copy"><p className="eyebrow light">CABINET D’AVOCATS · NOTAIRES · CONSEIL</p><h1>{identity.heroTitle}<br/><i>{identity.heroAccent}</i></h1><p className="hero-lead">{identity.heroText}</p><div className="hero-actions"><button className="button gold" onClick={()=>setBooking(true)}>Échanger avec le cabinet <ArrowRight size={16}/></button><a href="#expertises" className="text-link light-link">Découvrir nos expertises <ArrowDown size={15}/></a></div><div className="hero-stats"><div><b>15<span>+</span></b><small>ans d’expérience</small></div><div><b>04</b><small>domaines d’expertise</small></div><div><b>01</b><small>même exigence : la vôtre</small></div></div></div><div className="hero-visual"><div className="visual-frame"><div className="visual-image" style={{backgroundImage:`linear-gradient(180deg,rgba(16,40,32,.04),rgba(16,40,32,.28)),url("${identity.heroImage}")`}}></div><div className="visual-overlay"></div><div className="visual-caption"><span>CONSEIL · DÉFENSE · ACCOMPAGNEMENT</span><b>La confiance se construit.<br/>Le droit la protège.</b></div><div className="vertical-label">ABIDJAN · CÔTE D’IVOIRE</div></div><div className="hero-seal"><Scale size={31} strokeWidth={1.1}/><span>DEPUIS<br/><b>2011</b></span></div></div><div className="hero-index">01 <span>/</span> 04</div></section>
      <section className="trust-strip"><div><span className="strip-icon"><ShieldCheck/></span><p><b>Une parole claire</b><small>Des réponses compréhensibles, sans détour.</small></p></div><div><span className="strip-icon"><Scale/></span><p><b>Une expertise engagée</b><small>La rigueur au service de vos intérêts.</small></p></div><div><span className="strip-icon"><FileText/></span><p><b>Un suivi attentif</b><small>Un interlocuteur présent à chaque étape.</small></p></div></section>
      <section className="section about" id="cabinet"><div className="section-kicker reveal"><span>01 — LE CABINET</span><span className="kicker-line"/></div><div className="about-grid"><div className="about-title reveal"><p className="eyebrow">NOTRE ENGAGEMENT</p><h2>{identity.aboutTitle}<br/><i>{identity.aboutAccent}</i></h2><a className="text-link" href="#equipe">Rencontrer notre équipe <ArrowRight size={15}/></a></div><div className="about-text reveal"><p>{identity.aboutText}</p><p>{identity.aboutSecond}</p><div className="signature"><span className="sig-mark">E<span>&</span>C</span><span><b>La direction du cabinet</b><small>Étude & Conseil</small></span></div></div></div></section>
      <section className="expertise section" id="expertises"><div className="section-kicker reveal"><span>02 — NOS EXPERTISES</span><span className="kicker-line"/><span className="muted">UNE APPROCHE PLURIDISCIPLINAIRE</span></div><div className="expertise-head reveal"><h2>Le bon conseil,<br/><i>au bon moment.</i></h2><p>Nous croisons nos expertises pour apporter une réponse adaptée à votre situation — avec méthode, transparence et réactivité.</p></div><div className="service-grid">{editableServices.map(({title,text},index)=>{const Icon=[Landmark,FileText,HeartHandshake,ShieldCheck][index%4];const n=String(index+1).padStart(2,'0');return <article className="service-card reveal" key={title}><div className="service-top"><span>{n}</span><Icon size={23} strokeWidth={1.4}/></div><h3>{title}</h3><p>{text}</p><a href="#contact" aria-label={`En savoir plus : ${title}`}><ArrowUpRight size={18}/></a></article>})}</div><div className="expertise-bottom"><p>Vous ne savez pas vers quelle expertise vous tourner ?</p><button className="text-link" onClick={()=>setBooking(true)}>Décrivez-nous votre besoin <ArrowRight size={15}/></button></div></section>
      <section className="quote-band"><div className="quote-mark">“</div><blockquote>La confiance se gagne par l’écoute.<br/><i>Elle se confirme par les actes.</i></blockquote><span>NOTRE CONVICTION</span></section>
      <section className="section team" id="equipe"><div className="section-kicker reveal"><span>03 — L’ÉQUIPE</span><span className="kicker-line"/></div><div className="team-grid"><div className="team-copy reveal"><p className="eyebrow">DES COMPÉTENCES, UN MÊME ENGAGEMENT</p><h2>Des femmes et des hommes<br/><i>à vos côtés.</i></h2><p>Une équipe accessible et complémentaire, mobilisée pour comprendre vos enjeux et vous apporter des réponses concrètes.</p><button className="button dark" onClick={()=>setBooking(true)}>Prendre contact <ArrowRight size={16}/></button></div>{team.map((member,index)=><div className={`team-portrait reveal ${index%2?'second':''}`} key={index}><div className="portrait-image" style={{backgroundImage:`linear-gradient(180deg,transparent 46%,rgba(12,28,22,.55)),url("${member.image}")`}}></div><div className="portrait-card"><span>{member.role}</span><b>{member.name}</b><small>{member.bio}</small></div></div>)}</div></section>
      <section className="approach"><div className="approach-image" style={{backgroundImage:`linear-gradient(90deg,rgba(16,40,32,.1),rgba(16,40,32,.4)),url("${identity.approachImage}")`}}><div className="approach-caption"><span>NOTRE MÉTHODE</span><b>Chaque étape compte.</b></div></div><div className="approach-content"><p className="eyebrow light">UN ACCOMPAGNEMENT EN 3 TEMPS</p><h2>Vous savez toujours<br/><i>où vous en êtes.</i></h2><div className="steps"><div><b>01</b><p><strong>Écouter</strong><small>Comprendre votre situation et vos objectifs.</small></p></div><div><b>02</b><p><strong>Éclairer</strong><small>Vous présenter les options et leurs implications.</small></p></div><div><b>03</b><p><strong>Agir</strong><small>Définir et conduire la stratégie avec vous.</small></p></div></div></div></section>
      <section className="section insights" id="actualites"><div className="section-kicker reveal"><span>04 — CONSEILS & ACTUALITÉS</span><span className="kicker-line"/><a href="#contact">TOUS LES ARTICLES <ArrowRight size={14}/></a></div><div className="insights-head reveal"><h2>Le droit, en clair.</h2><p>Quelques repères pour mieux comprendre vos droits et anticiper vos décisions.</p></div><div className="article-grid">{articles.map((article,index)=><article className="article-card reveal" key={index}><div className={`article-art art-${['one','two','three'][index%3]}`}><FileText size={44}/><span>{article.category}</span></div><div className="article-meta">{article.category}</div><h3>{article.title}</h3><p>{article.body}</p></article>)}</div></section>
      <section className="contact-cta" id="contact"><div><p className="eyebrow light">UN PREMIER ÉCHANGE EN TOUTE CONFIDENTIALITÉ</p><h2>Faisons le point<br/><i>sur votre situation.</i></h2></div><button className="button gold" onClick={()=>setBooking(true)}>Demander un rendez-vous <ArrowRight size={16}/></button><div className="cta-orbit"></div></section>
      <section className="section faq" id="faq"><div className="section-kicker"><span>QUESTIONS FRÉQUENTES</span><span className="kicker-line"/></div><h2>Vos questions, nos réponses.</h2>{faq.map((item,i)=><details key={i}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</section>
    </main>
    <footer className="footer"><div className="footer-main"><div className="footer-brand"><a href="#accueil" className="brand"><span className="brand-icon"><Scale size={24}/></span><span><b>{identity.name}</b><small>{identity.type}</small></span></a><p>{identity.tagline}</p><div className="socials">{identity.linkedin&&<a href={identity.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin size={17}/></a>}{identity.instagram&&<a href={identity.instagram} target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram size={17}/></a>}</div></div><div className="footer-col"><b>EXPLORER</b><a href="#cabinet">Le cabinet</a><a href="#expertises">Nos expertises</a><a href="#equipe">L’équipe</a><a href="#actualites">Conseils</a></div><div className="footer-col"><b>CONTACT</b><a href={`tel:${identity.phone.replace(/\s/g,'')}`}><Phone size={14}/> {identity.phone}</a><a href={`mailto:${identity.email}`}><Mail size={14}/> {identity.email}</a><span><MapPin size={14}/> {identity.location}</span></div><div className="footer-col hours"><b>HORAIRES</b><span><Clock size={14}/> Lun – Ven</span><span>{identity.hours}</span><button onClick={()=>setBooking(true)}>Être rappelé <ArrowRight size={14}/></button></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {identity.name}. Tous droits réservés.</span><div><a href="#contact">Mentions légales</a><a href="#contact">Confidentialité</a><a href="#admin">Administration</a><span>Template de démonstration · contenus à personnaliser</span></div></div></footer>
    <button className="floating-booking" onClick={()=>setBooking(true)}><span>Prendre rendez-vous</span><ArrowUpRight size={17}/></button>
    {booking&&<BookingModal services={editableServices} availability={availability} onSubmit={submitRequest} onClose={()=>setBooking(false)}/>}
  </>;
}

createRoot(document.getElementById('root')).render(<App/>);
